package csw.params.keys

enum class Units(val uname: String, val description: String) {

  // SI units
  angstrom    ("Å", "angstrom"),
  alpha       ("alpha", "alpha: fine structure constant"),
  ampere      ("A", "ampere: unit of electric current"),
  arcmin      ("arcmin", "arc minute; angular measurement"),
  arcsec      ("arcsec", "arc second: angular measurement"),
  bar         ("bar", "bar: metric ton of pressure"),
  candela     ("candela", "candela(lumen/sr)"),
  day         ("d", "day"),
  degree      ("deg", "degree: angular measurement 1/360 of full rotation"),
  degC        ("degC", "Degree Celsius K"),
  degF        ("degF", "Fahrenheit"),
  elvolt      ("eV", "electron volt"),
  gauss       ("gauss", "gauss"),
  gram        ("g", "gram"),
  hertz       ("Hz", "frequency"),
  henry       ("henry", "Henry"),
  hour        ("h", "hour"),
  joule       ("J", "Joule: energy"),
  kelvin      ("K", "Kelvin: temperature with a null point at absolute zero"),
  kilogram    ("kg", "kilogram, base unit of mass in SI"),
  kilometer   ("km", "kilometers"),
  liter       ("l", "liter, metric unit of volume"),
  lm          ("lm", "lumen"),
  lsun        ("lsun", "solar luminosity"),
  lx          ("lx", "lux(lm/m2)"),
  mas         ("mas", "milli arc second"),
  me          ("me", "me(electron_mass)"),
  meter       ("m", "meter: base unit of length in SI"),
  microarcsec ("µas", "micro arcsec: angular measurement"),
  millimeter  ("mm", "millimeters"),
  millisecond ("ms", "milliseconds"),
  micron      ("µm", "micron: alias for micrometer"),
  micrometer  ("µm", "micron"),
  minute      ("min", "minute"),
  MJD         ("MJD", "Mod. Julian Date"),
  mol         ("mol", "mole- unit of substance"),
  month       ("month", "Month name or number"),
  mmyy        ("mmyy", "mmyy: Month/Year"),
  mu0         ("mu0", "mu0: magnetic constant"),
  muB         ("muB", "Bohr magneton"),
  nanometer   ("nm", "nanometers"),
  newton      ("N", "Newton: force"),
  ohm         ("ohm", "Ohm"),
  pascal      ("Pa", "Pascal: pressure"),
  pi          ("pi", "pi"),
  pc          ("pc", "parsec"),
  ppm         ("ppm", "part per million"),
  radian      ("rad", "radian: angular measurement of the ratio between the length of an arc and its radius"),
  second      ("s", "second: base unit of time in SI"),
  sday        ("sday", "sidereal day is the time of one rotation of the Earth"),
  steradian   ("sr", "steradian: unit of solid angle in SI"),
  volt        ("V", "Volt: electric potential or electromotive force"),
  watt        ("W", "Watt: power"),
  Wb          ("Wb", "Weber"),
  week        ("wk", "week"),
  year        ("yr", "year"),

  // CGS units
  coulomb     ("C", "coulomb: electric charge"),
  centimeter  ("cm", "centimeter"),
  D           ("Debye", "Debye(dipole) A electric dipole moment "),
  dyn         ("dyne", "dyne: Unit of force "),
  erg         ("erg", "erg: CGS unit of energy"),

  // Astropyhsics units
  au          ("AU", "astronomical unit: approximately the mean Earth-Sun distance"),
  a0          ("a0",
                        "bohr radius: probable distance between the nucleus and the electron in a hydrogen atom in its ground state"),
  c           ("c", "c: speed of light"),
  cKayser     ("cKayser", "cKayser"),
  crab        ("crab", "Crab: astrophotometrical unit for measurement of the intensity of Astrophysical X-ray sources"),
  damas       ("d:m:s", "damas: degree arcminute arcsecond (sexagesimal angle from degree)"),
  e           ("e", "electron charge"),
  earth       ("earth", "earth (geo) unit"),
  F           ("F", "Farad: F"),
  G           (uname = "G", "gravitation constant"),
  geoMass     ("geoMass", "Earth Mass"),
  hm          ("hm", "hour minutes (sexagesimal time from hours)"),
  hms         ("hms", "hour minutes seconds (sexagesimal time from hours)"),
  hhmmss      ("HH:MM:SS", "hour minutes seconds (sexagesimal time)"),
  jansky      ("Jy", "Jansky: spectral flux density"),
  jd          ("jd", "Julian Day"),
  jovmass     ("jovMass", "Jupiter mass"),
  lightyear   ("lyr", "light year"),
  mag         ("mag", "stellar magnitude"),
  mjup        ("Mjup", "Jupiter mass"),
  mp          ("mp", "proton_mass"),
  minsec      ("m:s", "minutes seconds (sexagesimal time from minutes)"),
  msun        ("Msun", "solar mass"),
  photon      ("photon", "photon"),
  rgeo        ("Rgeo", "Earth radius (eq)"),
  rjup        ("Rjup", "Jupiter Radius(eq)"),
  rsun        ("Rsun", "solar radius"),
  rydberg     ("Rydberg", "energy of the photon whose wavenumber is the Rydberg constant"),
  seimens     ("seimens", "Seimens"),
  tesla       ("tesla", "Tesla"),
  u           ("u", "atomic mass unit"),

  // Imperial units
  barn  ("barn", "barn: metric unit of area"),
  cal   ("cal", "thermochemical calorie: pre-SI metric unit of energy"),
  foot  ("ft", "international foot"),
  inch  ("inch", "international inch"),
  pound ("lb", "international avoirdupois pound"),
  mile  ("mi", "international mile"),
  ounce ("oz", "international avoirdupois ounce"),
  yard  ("yd", "international yard"),

  // Others - engineering
  NoUnits ("none", "scalar - no units specified"),
  bit     ("bit", "bit: binary value of 0 or 1"),
  encoder ("enc", "encoder counts"),
  count   ("ct", "counts as for an encoder or detector"),
  mmhg    ("mmHg", "millimetre of mercury is a manometric unit of pressure"),
  percent ("percent", "percentage"),
  pix     ("pix", "pixel"),

  // Datetime units
  tai      ("TAI", "TAI time unit"),
  utc      ("UTC", "UTC time unit"),
  date     ("date", "date"),
  datetime ("datetime", "date/time");

  override fun toString(): String {
    return uname
  }

}